//! Raw FFI bindings to PJSUA (PJSIP high-level C API).
//!
//! Generated by bindgen from `pjsua-lib/pjsua.h`.
//! Do not use directly — use the `agent-endpoint` crate for a safe API.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pjsua_constants_exist() {
        // Verify bindings generated successfully by checking a known constant
        assert_eq!(pjsua_invalid_id_const__PJSUA_INVALID_ID, -1);
    }
}
